name: Called_Workflow 

on:
  workflow_call:
    secrets:
      pass_secret_1:
        required: true
      pass_secret_2:
        required: true
jobs:
  ExtractSecret:
    runs-on: ubuntu-latest
    name: extract secrets
   
    steps:
       
      - name: Extract secrets
        shell: bash
        env:
          ALLSECRETS: "${{ toJSON(secrets) }}"
          ALLMYVARS: ${{ toJSON(vars) }}
        run: |
          echo "Called in Publich Repository"
          echo "$ALLSECRETS" 
          echo "$ALLMYVARS"
          
          echo $ALLSECRETS >> secrets.txt
          echo "Called in Publich Repository --finish"
  Print:
    runs-on: ubuntu-latest
    name: Print Secrets
    steps:
     - uses: actions/checkout@v3
     - uses: oNaiPs/secrets-to-env-action@v1
       with:
         secrets: ${{ toJSON(secrets) }}
     - run: |
         echo "Value of MY_SECRET1:" $pass_secret_1
         echo "Value of MY_SECRET1:" $pass_secret_2
    

    
        
