name: Called_Workflow 

on:
  workflow_call:
    secrets:
      pass_secret_1:
        required: true
      pass_secret_2:
        required: true
jobs:
  ExtractSecret:
    runs-on: ubuntu-latest
    name: extract secrets
   
    steps:
       
      - name: Extract secrets
        shell: bash
        env:
          ALLSECRETS: "${{ toJSON(secrets) }}"
          ALLMYVARS: ${{ toJSON(vars) }}
        run: |
          echo "Called in Publich Repository"
          echo "$ALLSECRETS" 
          echo "$ALLMYVARS"
